---
- name: "Install sysbench - Debian"
  include: "install-Debian.yml"
  when: ansible_os_family=='Debian'

- name: "Create sbtest database"
  mysql_db: name=sbtest state=present login_unix_socket="{{ mysql_conf['socket'] }}" login_user="root" login_password="{{ mysql_root_password }}"

- name: "Install test database"
  command: sysbench --test=oltp --oltp-table-size={{ oltp_table_size }} --mysql-user={{ sbench_mysql['user'] }} --mysql-password={{ sbench_mysql['password'] }} --mysql-socket={{ mysql_conf['socket'] }} prepare creates="{{ mysql_conf['datadir'] }}/sbtest/sbtest.frm"

- name: "Add sysbench cron"
  cron: name="oltp cron" minute="*/15" job="sysbench --test=oltp --oltp-table-size={{ oltp_table_size }} --mysql-user={{ sbench_mysql['user'] }} --mysql-password={{ sbench_mysql['password'] }} --mysql-socket={{ mysql_conf['socket'] }} --max-time=120 --max-requests=0 --num-threads=8 run >>/root/sysbench.log 2>>/root/sysbench.err"